/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserAnalyticsEntry = IDL.Record({
  'runningLogs' : IDL.Nat,
  'principal' : IDL.Principal,
  'issuedDay' : IDL.Int,
  'hydrationLogs' : IDL.Nat,
  'sleepLogs' : IDL.Nat,
  'profileName' : IDL.Text,
});
export const AnalyticsMetrics = IDL.Record({
  'weeklyActiveUsers' : IDL.Nat,
  'totalUniqueUsers' : IDL.Nat,
  'dailyActiveUsers' : IDL.Nat,
  'totalSleepEvents' : IDL.Nat,
  'totalHydrationEvents' : IDL.Nat,
  'totalRunningEvents' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HydrationLog = IDL.Record({
  'date' : IDL.Int,
  'totalIntake' : IDL.Float64,
});
export const RunningLog = IDL.Record({
  'pace' : IDL.Float64,
  'time' : IDL.Int,
  'completed' : IDL.Bool,
  'distance' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const SleepLog = IDL.Record({ 'hours' : IDL.Float64, 'date' : IDL.Int });
export const RewardType = IDL.Variant({
  'sleepyhead' : IDL.Null,
  'plastic_pirate' : IDL.Null,
  'runner' : IDL.Null,
  'hydrator' : IDL.Null,
});
export const UserRewards = IDL.Record({
  'lastGoalCompleteDay' : IDL.Int,
  'streak' : IDL.Nat,
  'badges' : IDL.Vec(RewardType),
  'lastUpdated' : IDL.Int,
  'completedGoals' : IDL.Nat,
});
export const UserData = IDL.Record({
  'dailyGoal' : IDL.Float64,
  'cupSize' : IDL.Float64,
});
export const CustomReminderDefinition = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'intervalInNanos' : IDL.Int,
  'enabled' : IDL.Bool,
  'lastSent' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
      [],
      [],
    ),
  'addDailyIntake' : IDL.Func([IDL.Float64], [], []),
  'addSleepLog' : IDL.Func([IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserAnalytics' : IDL.Func([], [IDL.Vec(UserAnalyticsEntry)], []),
  'getAnalyticsMetrics' : IDL.Func([], [AnalyticsMetrics], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIntakeHistory' : IDL.Func([], [IDL.Vec(HydrationLog)], ['query']),
  'getRunningHistory' : IDL.Func([], [IDL.Vec(RunningLog)], ['query']),
  'getSleepHistory' : IDL.Func([], [IDL.Vec(SleepLog)], ['query']),
  'getTodaysIntake' : IDL.Func([], [IDL.Float64], ['query']),
  'getTodaysRuns' : IDL.Func([], [IDL.Vec(RunningLog)], ['query']),
  'getTodaysSleep' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRewards' : IDL.Func([], [UserRewards], ['query']),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomReminders' : IDL.Func(
      [],
      [IDL.Vec(CustomReminderDefinition)],
      ['query'],
    ),
  'logRun' : IDL.Func([IDL.Float64, IDL.Int, IDL.Float64, IDL.Bool], [], []),
  'removeCustomReminder' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomReminder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
      [],
      [],
    ),
  'updateUserSettings' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserAnalyticsEntry = IDL.Record({
    'runningLogs' : IDL.Nat,
    'principal' : IDL.Principal,
    'issuedDay' : IDL.Int,
    'hydrationLogs' : IDL.Nat,
    'sleepLogs' : IDL.Nat,
    'profileName' : IDL.Text,
  });
  const AnalyticsMetrics = IDL.Record({
    'weeklyActiveUsers' : IDL.Nat,
    'totalUniqueUsers' : IDL.Nat,
    'dailyActiveUsers' : IDL.Nat,
    'totalSleepEvents' : IDL.Nat,
    'totalHydrationEvents' : IDL.Nat,
    'totalRunningEvents' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HydrationLog = IDL.Record({
    'date' : IDL.Int,
    'totalIntake' : IDL.Float64,
  });
  const RunningLog = IDL.Record({
    'pace' : IDL.Float64,
    'time' : IDL.Int,
    'completed' : IDL.Bool,
    'distance' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const SleepLog = IDL.Record({ 'hours' : IDL.Float64, 'date' : IDL.Int });
  const RewardType = IDL.Variant({
    'sleepyhead' : IDL.Null,
    'plastic_pirate' : IDL.Null,
    'runner' : IDL.Null,
    'hydrator' : IDL.Null,
  });
  const UserRewards = IDL.Record({
    'lastGoalCompleteDay' : IDL.Int,
    'streak' : IDL.Nat,
    'badges' : IDL.Vec(RewardType),
    'lastUpdated' : IDL.Int,
    'completedGoals' : IDL.Nat,
  });
  const UserData = IDL.Record({
    'dailyGoal' : IDL.Float64,
    'cupSize' : IDL.Float64,
  });
  const CustomReminderDefinition = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'intervalInNanos' : IDL.Int,
    'enabled' : IDL.Bool,
    'lastSent' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
        [],
        [],
      ),
    'addDailyIntake' : IDL.Func([IDL.Float64], [], []),
    'addSleepLog' : IDL.Func([IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserAnalytics' : IDL.Func([], [IDL.Vec(UserAnalyticsEntry)], []),
    'getAnalyticsMetrics' : IDL.Func([], [AnalyticsMetrics], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIntakeHistory' : IDL.Func([], [IDL.Vec(HydrationLog)], ['query']),
    'getRunningHistory' : IDL.Func([], [IDL.Vec(RunningLog)], ['query']),
    'getSleepHistory' : IDL.Func([], [IDL.Vec(SleepLog)], ['query']),
    'getTodaysIntake' : IDL.Func([], [IDL.Float64], ['query']),
    'getTodaysRuns' : IDL.Func([], [IDL.Vec(RunningLog)], ['query']),
    'getTodaysSleep' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRewards' : IDL.Func([], [UserRewards], ['query']),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomReminders' : IDL.Func(
        [],
        [IDL.Vec(CustomReminderDefinition)],
        ['query'],
      ),
    'logRun' : IDL.Func([IDL.Float64, IDL.Int, IDL.Float64, IDL.Bool], [], []),
    'removeCustomReminder' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomReminder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
        [],
        [],
      ),
    'updateUserSettings' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };