/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsMetrics {
  'weeklyActiveUsers' : bigint,
  'totalUniqueUsers' : bigint,
  'dailyActiveUsers' : bigint,
  'totalSleepEvents' : bigint,
  'totalHydrationEvents' : bigint,
  'totalRunningEvents' : bigint,
}
export interface CustomReminderDefinition {
  'name' : string,
  'description' : string,
  'intervalInNanos' : bigint,
  'enabled' : boolean,
  'lastSent' : bigint,
}
export interface HydrationLog { 'date' : bigint, 'totalIntake' : number }
export type RewardType = { 'sleepyhead' : null } |
  { 'plastic_pirate' : null } |
  { 'runner' : null } |
  { 'hydrator' : null };
export interface RunningLog {
  'pace' : number,
  'time' : bigint,
  'completed' : boolean,
  'distance' : number,
  'timestamp' : bigint,
}
export interface SleepLog { 'hours' : number, 'date' : bigint }
export interface UserAnalyticsEntry {
  'runningLogs' : bigint,
  'principal' : Principal,
  'issuedDay' : bigint,
  'hydrationLogs' : bigint,
  'sleepLogs' : bigint,
  'profileName' : string,
}
export interface UserData { 'dailyGoal' : number, 'cupSize' : number }
export interface UserProfile { 'name' : string }
export interface UserRewards {
  'streak' : bigint,
  'badges' : Array<RewardType>,
  'lastUpdated' : bigint,
  'completedGoals' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Custom Reminders System
   */
  'addCustomReminder' : ActorMethod<
    [string, string, bigint, boolean],
    undefined
  >,
  'addDailyIntake' : ActorMethod<[number], undefined>,
  /**
   * / Sleep Tracking
   */
  'addSleepLog' : ActorMethod<[number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserAnalytics' : ActorMethod<[], Array<UserAnalyticsEntry>>,
  'getAnalyticsMetrics' : ActorMethod<[], AnalyticsMetrics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIntakeHistory' : ActorMethod<[], Array<HydrationLog>>,
  'getRunningHistory' : ActorMethod<[], Array<RunningLog>>,
  'getSleepHistory' : ActorMethod<[], Array<SleepLog>>,
  'getTodaysIntake' : ActorMethod<[], number>,
  'getTodaysRuns' : ActorMethod<[], Array<RunningLog>>,
  'getTodaysSleep' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Rewards & Gamification
   */
  'getUserRewards' : ActorMethod<[], UserRewards>,
  'getUserSettings' : ActorMethod<[], [] | [UserData]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomReminders' : ActorMethod<[], Array<CustomReminderDefinition>>,
  /**
   * / Running Tracker
   */
  'logRun' : ActorMethod<[number, bigint, number, boolean], undefined>,
  'removeCustomReminder' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomReminder' : ActorMethod<
    [string, string, bigint, boolean],
    undefined
  >,
  /**
   * / Hydration Tracking
   */
  'updateUserSettings' : ActorMethod<[number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];