/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SleepLog {
    hours: number;
    date: bigint;
}
export interface RunningLog {
    pace: number;
    time: bigint;
    completed: boolean;
    distance: number;
    timestamp: bigint;
}
export interface CustomReminderDefinition {
    name: string;
    description: string;
    intervalInNanos: bigint;
    enabled: boolean;
    lastSent: bigint;
}
export interface AnalyticsMetrics {
    weeklyActiveUsers: bigint;
    totalUniqueUsers: bigint;
    dailyActiveUsers: bigint;
    totalSleepEvents: bigint;
    totalHydrationEvents: bigint;
    totalRunningEvents: bigint;
}
export interface UserRewards {
    streak: bigint;
    badges: Array<RewardType>;
    lastUpdated: bigint;
    completedGoals: bigint;
}
export interface UserAnalyticsEntry {
    runningLogs: bigint;
    principal: Principal;
    issuedDay: bigint;
    hydrationLogs: bigint;
    sleepLogs: bigint;
    profileName: string;
}
export interface HydrationLog {
    date: bigint;
    totalIntake: number;
}
export interface UserData {
    dailyGoal: number;
    cupSize: number;
}
export interface UserProfile {
    name: string;
}
export enum RewardType {
    sleepyhead = "sleepyhead",
    plastic_pirate = "plastic_pirate",
    runner = "runner",
    hydrator = "hydrator"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Custom Reminders System
     */
    addCustomReminder(name: string, description: string, interval: bigint, enabled: boolean): Promise<void>;
    addDailyIntake(amount: number): Promise<void>;
    /**
     * / Sleep Tracking
     */
    addSleepLog(hours: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllUserAnalytics(): Promise<Array<UserAnalyticsEntry>>;
    getAnalyticsMetrics(): Promise<AnalyticsMetrics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIntakeHistory(): Promise<Array<HydrationLog>>;
    getRunningHistory(): Promise<Array<RunningLog>>;
    getSleepHistory(): Promise<Array<SleepLog>>;
    getTodaysIntake(): Promise<number>;
    getTodaysRuns(): Promise<Array<RunningLog>>;
    getTodaysSleep(): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Rewards & Gamification
     */
    getUserRewards(): Promise<UserRewards>;
    getUserSettings(): Promise<UserData | null>;
    isCallerAdmin(): Promise<boolean>;
    listCustomReminders(): Promise<Array<CustomReminderDefinition>>;
    /**
     * / Running Tracker
     */
    logRun(distance: number, time: bigint, pace: number, completed: boolean): Promise<void>;
    removeCustomReminder(name: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCustomReminder(name: string, description: string, interval: bigint, enabled: boolean): Promise<void>;
    /**
     * / Hydration Tracking
     */
    updateUserSettings(dailyGoal: number, cupSize: number): Promise<void>;
}
import type { RewardType as _RewardType, UserData as _UserData, UserProfile as _UserProfile, UserRewards as _UserRewards, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomReminder(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomReminder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomReminder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addDailyIntake(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyIntake(arg0);
            return result;
        }
    }
    async addSleepLog(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSleepLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSleepLog(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllUserAnalytics(): Promise<Array<UserAnalyticsEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserAnalytics();
            return result;
        }
    }
    async getAnalyticsMetrics(): Promise<AnalyticsMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsMetrics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntakeHistory(): Promise<Array<HydrationLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntakeHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntakeHistory();
            return result;
        }
    }
    async getRunningHistory(): Promise<Array<RunningLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRunningHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRunningHistory();
            return result;
        }
    }
    async getSleepHistory(): Promise<Array<SleepLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSleepHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSleepHistory();
            return result;
        }
    }
    async getTodaysIntake(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysIntake();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysIntake();
            return result;
        }
    }
    async getTodaysRuns(): Promise<Array<RunningLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysRuns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysRuns();
            return result;
        }
    }
    async getTodaysSleep(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysSleep();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysSleep();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRewards(): Promise<UserRewards> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRewards();
                return from_candid_UserRewards_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRewards();
            return from_candid_UserRewards_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomReminders(): Promise<Array<CustomReminderDefinition>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomReminders();
            return result;
        }
    }
    async logRun(arg0: number, arg1: bigint, arg2: number, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logRun(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logRun(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async removeCustomReminder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCustomReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCustomReminder(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCustomReminder(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomReminder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomReminder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateUserSettings(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0, arg1);
            return result;
        }
    }
}
function from_candid_RewardType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardType): RewardType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRewards_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRewards): UserRewards {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserData]): UserData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streak: bigint;
    badges: Array<_RewardType>;
    lastUpdated: bigint;
    completedGoals: bigint;
}): {
    streak: bigint;
    badges: Array<RewardType>;
    lastUpdated: bigint;
    completedGoals: bigint;
} {
    return {
        streak: value.streak,
        badges: from_candid_vec_n8(_uploadFile, _downloadFile, value.badges),
        lastUpdated: value.lastUpdated,
        completedGoals: value.completedGoals
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sleepyhead: null;
} | {
    plastic_pirate: null;
} | {
    runner: null;
} | {
    hydrator: null;
}): RewardType {
    return "sleepyhead" in value ? RewardType.sleepyhead : "plastic_pirate" in value ? RewardType.plastic_pirate : "runner" in value ? RewardType.runner : "hydrator" in value ? RewardType.hydrator : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RewardType>): Array<RewardType> {
    return value.map((x)=>from_candid_RewardType_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
